version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: elysiaAuth
      POSTGRES_USER: ilkay
      POSTGRES_PASSWORD: secretPassword
    ports:
      - "5432:5432"
